title: Analysis on Recipes
description: Investigation on the relationship betweeen calories, average recipe rating, and preparation time.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
